package com.sk.directudhar.ui.mandate

import java.io.Serializable

class Request: Serializable {
    val Channel: String = ""
    val CheckSum: String = ""
    val Customer_AccountNo: String = ""
    val Customer_DebitAmount: Any = ""
    val Customer_DebitFrequency: String = ""
    val Customer_EmailId: String = ""
    val Customer_ExpiryDate: String = ""
    val Customer_InstructedMemberId: String = ""
    val Customer_MaxAmount: String = ""
    val Customer_Mobile: String = ""
    val Customer_Name: String = ""
    val Customer_Reference1: Any = ""
    val Customer_Reference2: Any = ""
    val Customer_SequenceType: String = ""
    val Customer_StartDate: String = ""
    val Filler1: Any = ""
    val Filler10: Any = ""
    val Filler2: Any = ""
    val Filler3: Any = ""
    val Filler4: Any = ""
    val Filler5: String = ""
    val Filler6: Any = ""
    val Filler7: Any = ""
    val Filler8: Any = ""
    val Filler9: Any = ""
    val Merchant_Category_Code: String = ""
    val MsgId: String = ""
    val Short_Code: String = ""
    val UtilCode: String = ""
}