package com.sk.directudhar.ui.businessDetails

class ServiceProvide {
    companion object {
        fun getServiceProvider():ArrayList<ServiceProvider>{
            val mList :ArrayList<ServiceProvider> = ArrayList()
            mList.add(ServiceProvider(0,"None","None"))
            mList.add(ServiceProvider(1,"AJMER","Ajmer Vidhyut Vitran Nigam Ltd (AJMER)"))
            mList.add(ServiceProvider(2,"APDCL","Assam Power Distribution Company Limited (APDCL))"))
            mList.add(ServiceProvider(3,"BSES_DL","BSES Yamuna Power Ltd / BSES Rajdhani Power Ltd (BSES_DL)"))
            mList.add(ServiceProvider(4,"BESCOM","Bangalore Electricity Supply Company Ltd (BESCOM)"))
            mList.add(ServiceProvider(5,"BEST_MH","Brihanmumbai Electric Supply &amp; Transport Undertaking for Greater Mumbai (BEST_MH)"))
            mList.add(ServiceProvider(6,"CESC","Calcutta Electric Supply Corporation Limited (CESC)"))
            mList.add(ServiceProvider(7,"CESCOM","Chamundeshwari Electricity Supply Company Limited Mysore"))
            mList.add(ServiceProvider(8,"CH_ELEC","Chandigarh Electricity Department (CH_ELEC)"))
            mList.add(ServiceProvider(9,"CSPDCL","Chhattisgarh State Power Distribution Company Limited (CSPDCL)"))
            mList.add(ServiceProvider(10,"DGVCL","Dakshin Gujarat VIJ Company Limited (DGVCL)"))
            mList.add(ServiceProvider(11,"DHBVN","Dakshin Haryana Bijli Vitran Nigam (DHBVN)"))
            mList.add(ServiceProvider(12,"DAMAN_DIU","Daman and Diu Electricity Department (DAMAN_DIU)"))
            mList.add(ServiceProvider(13,"APEPDCL","Eastern Power Distribution Company of Andhra Pradesh Limited (APEPDCL)"))
            mList.add(ServiceProvider(14,"GOA_ELEC","Goa Electricity- for Tisvadi, Ponda &amp; Verna (GOA_ELEC)"))
            mList.add(ServiceProvider(15,"UPAY_GOA","Goa Electricity- for others (UPAY_GOA)"))
            mList.add(ServiceProvider(16,"GESCOM","Gulbarga Electricity Supply Company Limited (GESCOM)"))
            mList.add(ServiceProvider(17,"HPSEB","Himachal Pradesh State Electricity Board Ltd (HPSEB)"))
            mList.add(ServiceProvider(18,"HESCOM","Hubli Electricity Supply Company Limited (HESCOM)"))
            mList.add(ServiceProvider(19,"JAIPUR","Jaipur Vidhyut Vitran Nigam Ltd (JAIPUR)"))
            mList.add(ServiceProvider(20,"JODHPUR","Jodhpur Vidhyut Vitran Nigam Ltd (JODHPUR)"))
            mList.add(ServiceProvider(21,"KESCO","Kanpur Electricity Supply Company (KESCO)"))
            mList.add(ServiceProvider(22,"KERALA","Kerala State Electricity Board (KERALA)"))
            mList.add(ServiceProvider(23,"MAHAVITRAN","MAHAVITARAN-Maharashtra State Electricity Distribution Co. Ltd (MSEDCL)"))
            mList.add(ServiceProvider(24,"MGVCL","Madhya Gujarat VIJ Company Limited (MGVCL)"))
            mList.add(ServiceProvider(25,"MPCZ","Madhya Pradesh Madhya Kshetra Vidyut Vitran Company Limited (MPCZ)"))
            mList.add(ServiceProvider(26,"MPWZ","Madhya Pradesh Paschim Kshetra Vidyut Vitran Company Limited (MPWZ)"))
            mList.add(ServiceProvider(27,"MPEZ","Madhya Pradesh Poorv Kshetra Vidyut Vitran Company Limited (MPEZ)"))
            mList.add(ServiceProvider(28,"MESCOM","Mangalore Electricity Supply Company Limited (MESCOM)"))
            mList.add(ServiceProvider(29,"MeECL","Meghalaya Energy Corporation Limited (MeECL)"))
            mList.add(ServiceProvider(30,"NBPDCL","North Bihar Power Distribution Company Limited (NBPDCL)"))
            mList.add(ServiceProvider(31,"PGVCL","Pashchim Gujarat VIJ Company Ltd. (PGVCL)"))
            mList.add(ServiceProvider(33,"PSPCL","Punjab State Power Corporation Limited (PSPCL)"))
            mList.add(ServiceProvider(33,"SBPDCL","South Bihar Power Distribution Company Limited (SBPDCL)"))
            mList.add(ServiceProvider(34,"APSPDCL","Southern Power Distribution Company of Andhra Pradesh Limited (APSPDCL)"))
            mList.add(ServiceProvider(35,"ORISSA","Supply Company of Orissa Limited (North, South, West, Central) (ORISSA)"))
            mList.add(ServiceProvider(36,"TATA_MUMBAI","TATA-Power - Mumbai (TATA_MUMBAI)"))
            mList.add(ServiceProvider(37,"CHENNAI_NORTH","Tamil Nadu Generation and Distribution Corporation Limited - Chennai_North"))
            mList.add(ServiceProvider(38,"CHENNAI_SOUTH","Tamil Nadu Generation and Distribution Corporation Limited - Chennai_South"))
            mList.add(ServiceProvider(39,"COIMBATORE","Tamil Nadu Generation and Distribution Corporation Limited - Coimbatore"))
            mList.add(ServiceProvider(40,"ERODE","Tamil Nadu Generation and Distribution Corporation Limited - Erode"))
            mList.add(ServiceProvider(41,"MADURAI","Tamil Nadu Generation and Distribution Corporation Limited - Madurai"))
            mList.add(ServiceProvider(42,"TIRUNELVEL","Tamil Nadu Generation and Distribution Corporation Limited - Tirunelvel"))
            mList.add(ServiceProvider(43,"TRICHY","Tamil Nadu Generation and Distribution Corporation Limited - Trichy"))
            mList.add(ServiceProvider(44,"VELLORE","Tamil Nadu Generation and Distribution Corporation Limited - Vellore"))
            mList.add(ServiceProvider(45,"VILLUPURAM","Tamil Nadu Generation and Distribution Corporation Limited - Villupuram"))
            mList.add(ServiceProvider(46,"TATA_DL","Tata Power Delhi Distribution (TATA_DL)"))
            mList.add(ServiceProvider(47,"TSSPCL","The Southern Power Distribution Company of Telangana Limited (TSSPCL)"))
            mList.add(ServiceProvider(48,"TORRENT_AGRA","Torrent Power Limited - Agra (TORRENT_AGRA)"))
            mList.add(ServiceProvider(49,"TORRENT_AHD","Torrent Power Limited - Ahmedabad (TORRENT_AHD)"))
            mList.add(ServiceProvider(50,"TORRENT_BHIWANDI","Torrent Power Limited - Bhiwandi (TORRENT_BHIWANDI)"))
            mList.add(ServiceProvider(51,"TORRENT_DAHEJ","Torrent Power Limited - Dahej (TORRENT_DAHEJ)"))
            mList.add(ServiceProvider(52,"TORRENT_SURAT","Torrent Power Limited - Surat (TORRENT_SURAT)"))
            mList.add(ServiceProvider(53,"TRIPURA","Tripura State Electricity Corporation Limited (TRIPURA)"))
            mList.add(ServiceProvider(54,"UPPCL","UP Vidyut Vitran Nigam Limited (All Zones) (UPPCL)"))
            mList.add(ServiceProvider(55,"UGVCL","Uttar Gujarat VIJ Company Ltd. (UGVCL)"))
            mList.add(ServiceProvider(56,"UHBVN","Uttar Haryana Bijli Vitran Nigam (UHBVN)"))
            mList.add(ServiceProvider(57,"UHBVN","WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED (WBENGAL)"))

            return mList
        }
    }
}